#:kivy 1.10.1
#:import MeshLinePlot kivy.garden.graph.MeshLinePlot

BSOFGraph:
<BSOFGraph>:
  graph : graph
  Graph:
    id: graph
    plot: MeshLinePlot
    xlabel: 'X'
    ylabel: 'Y'
    x_ticks_minor: 5
    x_tics_major: 25
    y_ticks_major: 1
    y_grid_label: True
    x_grid_label: True
    padding: 5
    x_grid: True
    y_grid: True
    xmin: -0
    xmax: 100
    ymin: -1
    ymax: 1
    # hard code
    pos: 1000, 400
    size: 600, 600
